### ISSUE TITLE
`search.shift` broken with new update

### ISSUE THREAD

**Issue by diogoprov** [pasraia/RRphylo#1]
I have used `RRphylo::search.shift` last year and it worked perfectly. But with the new update, there seems to be something wrong with my 1 year old code. 

I'm trying to estimate rate shifts for a multivariate data set. `fish.scores[,1:3]` is the first three eigenvectors from a phylogenetic PCA:

```
taxas_evol <- RRphylo(fish_tree, fish_scores[,1:3])
head(taxas_evol)
tip_pheno <- taxas_evol$rates[15:29,]
Evol_Rates <- taxas_evol$rates
shift_hemacia <- search.shift(taxas_evol, status.type = "clade", auto.recognize = "yes", foldername = tempdir())
```

I saw that the `auto.recognize = "yes"` argument is now deprecated. However, when I just remove it from the function I get the following error now:

```
Error in data.frame(`rate difference` = l2N.init[match(names(p.init),  : 
  object 'l2N.init' not found
```

I don't have a clue what's happening. 

Apprezzo se è possibile verificare questo per me. 

Gracie mille,
Diogo

**Comment by pasraia** [comment]
Dear Diogo,
We believe we found the error. It's a very rare condition it seems we overlooked. Please try the 2.4.1 version we are uploading right now, it should work fine.
Many thanks for posting this up
Pas & Silvia

**Comment by diogoprov** [comment]
Bravo! 
Grazie mille, yes the v. 2.4.1 worked perfectly now. I was able to reproduce the same result as before. 

abbraccio a voi,
Diogo

**Comment by pasraia** [comment]
Glad to help Diogo,and congrats on your Italian!On Feb 5, 2020 18:18, "Diogo B. Provete" <notifications@github.com> wrote:Bravo!
Grazie mille, yes the v. 2.4.1 worked perfectly now. I was able to reproduce the same result as before.
abbraccio a voi,
Diogo
