### ISSUE TITLE
Error happened in search.shift function

### ISSUE THREAD

**Issue by kumimatsui** [pasraia/RRphylo#4]
Dear pasraia

While I am using search.shift function following https://cran.r-project.org/web/packages/RRphylo/vignettes/overfitRR.html, an error, "Error in paste(filename, ".pdf", sep = "") :   argument "filename" is missing, with no default" , was displayed in my console. I tried to use both my own data and sample data, DataOrnithodirans, but the results were the same. If you have any ideas about the error, could you please let me know?

Thanks
KM

**Comment by pasraia** [comment]
Hi KM,
thanks for contacting me for help. I think the problem could be solved by installing the latest version (2.7.0) of RRphylo available on CRAN. 
Please let me know if this fixes your issue.

Cheers,
Pas

**Comment by kumimatsui** [comment]
Hi Pas

Thanks very much for your response. I updated to RRphylo 2.7 but the same error happened.

KM

**Comment by pasraia** [comment]
Thanks for notifying. 
Could you be so kind to report the code line generating the error?

Pas

**Comment by kumimatsui** [comment]
Hi Pas

After the last replay, I tried to update my R to R4.2.2. The problem was resolved. I'm sorry for bothering you and thanks very much for your kind responses.

Best
KM

**Comment by pasraia** [comment]
I'm glad it works now. Thanks again for contacting me.

Cheers,
Pas
