### ISSUE TITLE
Multicore for univariate trait?

### ISSUE THREAD

**Issue by diogoprov** [pasraia/RRphylo#5]
Salve Silvia e @pasraia, come stai?
I'm having a bit of a hassle trying to use RRphylo to estimate the rate of evolution of body size on a 9,000 tip phylogeny of birds. Because it's not a multivariate trait, the function doesn't allow me to use multicore. It's been running on a 12-core AMD with 128 GB RAM for almost one month, but it's only using ~ 5% of the processing capacity. 

Do you have any idea how we can deal with this situation? 

Our initial question was to estimate the tip-based rate of evolution for body size for the regional pool of species occurring in the Brazilian Atlantic Forest, and we were simply prunning the big MCCT to only include those species, but after some thought we decided to first estimate the rate for the tree including all the most MRCA of the species in the Atlantic Forest and only then prune the tree. This became a nightmare :)

Any thoughts?

**Comment by pasraia** [comment]
Hi Diogo,
thanks for reaching out on us. We're a bit surprised from your reports. We ran RRphylo on >7000 species wide trees and took a couple of hours to complete on a machine not very different from yours. There are a couple of possible explanations. The first regards data formatting, or it could be the likelihood surface is very flat hence the optimization process gets stuck somehow. We see two possible workarounds. The first is to narrow down the parameter space in the likelihood part (lambda estimation). The second is to narrow down the tree. If you're interested in Atlantic Forest species only, maybe fairy wren or red billed quelea are adding nothing to your inquiry, correct? In any instance, we would like to investigate more upon this. If you like, you could forward us an Rda file with the data to let us check. If you're preoccupied with data sharing, just change the tip names like:

sample(apply(combn(letters,4),2,paste,collapse=""),Ntip(tree))->new_names
tree$tip,label<-new_names
names(y)<-new_names


looking forward to hear from you
Pas and Silvia

**Comment by diogoprov** [comment]
Salve Silvia e Pasquale,
grazie mille un'altra volta for responding so quickly. We've been reworking our data, double checking some stuff and we plan to send it an .Rdata to you asap. But maybe you have already found the error: we were using a much larger species set than we actually needed. We'll run RRphylo again only with the MRCA of the species in the Atlantic Forest and see what happens.

Grazie per tutto ! Buona settimana a voi
